const os = require('os')

console.log(`Sistema Operacional: ${os.platform()}`)
console.log(`Usuário: ${os.hostname()}`)
console.log(`Arquitetura: ${os.arch()}`)
console.log(`Número de cpus: ${os.cpus().length}`)
console.log(os.type())
console.log(os.userInfo())
console.log(os.version())
console.log(os.totalmem())
console.log(os.tmpdir())
console.log(os.constants)
console.log(os.networkInterfaces())
console.log(os.homedir())
